---
php_packages:
  - php8.1
  - libapache2-mod-php8.1
  - php8.1-mysql
  - php8.1-cgi
  - php8.1-fpm
  - php8.1-cli
  - php8.1-curl
  - php8.1-gd
  - php8.1-imap
  - php8.1-mbstring
  - php8.1-intl
  - php8.1-apcu
  - php8.1-common
  - php8.1-bcmath
  - php8.1-xml